/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Initializable__factory>;
    getContractFactory(
      name: "Sahara",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Sahara__factory>;
    getContractFactory(
      name: "SaharaV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SaharaV2__factory>;
    getContractFactory(
      name: "SaharaV3",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SaharaV3__factory>;
    getContractFactory(
      name: "SaharaV4",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SaharaV4__factory>;

    getContractAt(
      name: "Initializable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Initializable>;
    getContractAt(
      name: "Sahara",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Sahara>;
    getContractAt(
      name: "SaharaV2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SaharaV2>;
    getContractAt(
      name: "SaharaV3",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SaharaV3>;
    getContractAt(
      name: "SaharaV4",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SaharaV4>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
